**Import Libraries**

In [4]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [ ]:
Upload Data

In [49]:
df = pd.read_csv('Record.csv')
df.shape
#df

(5000, 5)

In [13]:
df.Gender.unique()

array(['Other', 'Male', 'Female'], dtype=object)

In [14]:
df.Grade.unique()

array(['High School', 'Undergraduate', 'Postgraduate'], dtype=object)

In [15]:
df.Result.unique()

array(['Good', 'Poor', 'Average'], dtype=object)

In [16]:
df.Gender.value_counts()

Gender
Male      1719
Other     1651
Female    1630
Name: count, dtype: int64

In [17]:
df.isnull().sum()

ID        0
Age       6
Gender    0
Grade     0
Result    0
dtype: int64

**Split data into train and test before doing encoders**

In [20]:
from sklearn.model_selection import train_test_split
(X_train,X_test,y_train,y_test)= train_test_split(df.drop(columns=['Result']),df['Result'],test_size=0.2,random_state=2)

In [25]:
X_train
#X_train.shape

        ID   Age  Gender          Grade
868    869  18.0  Female  Undergraduate
936    937  21.0  Female  Undergraduate
4034  4035  23.0   Other  Undergraduate
1923  1924  24.0    Male    High School
3330  3331  19.0   Other  Undergraduate
...    ...   ...     ...            ...
3335  3336  16.0  Female   Postgraduate
1099  1100  18.0  Female   Postgraduate
2514  2515  17.0    Male    High School
3606  3607  22.0   Other    High School
2575  2576  19.0    Male  Undergraduate

[4000 rows x 4 columns]

In [24]:
X_test.shape

(1000, 4)

**Using all encoders seperately**

In [44]:
#Simple Imputer for missing values
si = SimpleImputer()
X_train_Age = si.fit_transform(X_train[['Age']])
X_test_Age = si.transform(X_test[['Age']])
X_train_Age.shape

(4000, 1)

In [33]:
# Ordinal Encoder for Ordinal categorical data
oe = OrdinalEncoder(categories=[['High School','Undergraduate','Postgraduate']])
X_train_Grade = oe.fit_transform(X_train[['Grade']])
X_test_Grade = oe.transform(X_test[['Grade']])
X_train_Grade.shape

(4000, 1)

In [39]:
# OneHot Encoding for Nominal categorical data
ohe = OneHotEncoder(drop = 'first')
X_train_Gender = ohe.fit_transform(X_train[['Gender']])
X_test_Gender = ohe.transform(X_test[['Gender']])
X_train_Gender.shape

(4000, 2)

In [45]:
#Extracting ID
X_train_ID = X_train[['ID']].values
X_test_ID = X_test[['ID']].values
X_train_ID.shape

(4000, 1)

In [41]:
#Extracting Age
X_train_Age = X_train[['Age']].values
X_test_ID = X_test[['Age']].values
X_train_Age.shape

(4000, 1)

In [48]:
X_train_transformed = np.concatenate((X_train_ID, X_train_Age, X_train_Gender.toarray(), X_train_Grade), axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_ID, X_test_Age, X_test_Gender.toarray(), X_test_Grade), axis=1)

X_train_transformed.shape

(4000, 5)

**Use of Column transfer**

In [50]:
from sklearn.compose import ColumnTransformer

In [52]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['Age']),
    ('tnf2',OrdinalEncoder(categories=[['High School','Undergraduate','Postgraduate']]),['Grade']),
    ('tnf3',OneHotEncoder(drop='first'),['Gender'])
],remainder='passthrough')

In [53]:
transformer.fit_transform(X_train).shape

(4000, 5)

In [54]:
transformer.transform(X_test).shape

(1000, 5)